### ISSUE TITLE
`make_SampleQC_report` does not render on server

### ISSUE THREAD

**Issue by khembach** [wmacnair/SampleQC#11]
I tried to render the report on the server, but got following error: `unable to start device PNG` and the warning `unable to open connection to X11 display`. Using `cairo` pngs fixed this for me. I tried `knitr::opts_chunk$set( autodep=TRUE, cache=FALSE, dev='png', dev.args = list(png = list(type = "cairo")))` in the setup and the html rendered sucessfully.

**Comment by wmacnair** [comment]
Closed because could not replicate.
