### ISSUE TITLE
Installation Issue (Windows 10, R 4.1.1)

### ISSUE THREAD

**Issue by mdmanurung** [wmacnair/SampleQC#23]
Dear author,

I encounter some trouble in building the package.

<details>
<summary> Here is the error output</summary>
<p>

Warning message:
Project requested R version '4.0.2' but '4.1.1' is currently being used 
* installing *source* package 'SampleQC' ...
** using staged installation
** libs
"C:/rtools40/mingw64/bin/"g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-41~1.1/include" -DNDEBUG  -I'C:/Users/mdmanurung/Dropbox/PhD/projects/czi-scrnaseq/renv/library/R-4.1/x86_64-w64-mingw32/Rcpp/include' -I'C:/Users/mdmanurung/Dropbox/PhD/projects/czi-scrnaseq/renv/library/R-4.1/x86_64-w64-mingw32/RcppDist/include' -I'C:/Users/mdmanurung/Dropbox/PhD/projects/czi-scrnaseq/renv/library/R-4.1/x86_64-w64-mingw32/RcppArmadillo/include'     -fopenmp   -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c RcppExports.cpp -o RcppExports.o
RcppExports.cpp:10:123: error: 'uint' has not been declared
 List fit_sampleqc_mle_cpp(arma::mat x, arma::mat init_gamma_i, arma::uvec groups, int D, int J, int K, int N, int n_iter, uint seed);
                                                                                                                           ^~~~
RcppExports.cpp: In function 'SEXPREC* _SampleQC_fit_sampleqc_mle_cpp(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)':
RcppExports.cpp:23:36: error: 'uint' was not declared in this scope
     Rcpp::traits::input_parameter< uint >::type seed(seedSEXP);
                                    ^~~~
RcppExports.cpp:23:36: note: suggested alternative: 'Sint'
     Rcpp::traits::input_parameter< uint >::type seed(seedSEXP);
                                    ^~~~
                                    Sint
RcppExports.cpp:23:41: error: template argument 1 is invalid
     Rcpp::traits::input_parameter< uint >::type seed(seedSEXP);
                                         ^
RcppExports.cpp:23:49: error: expected initializer before 'seed'
     Rcpp::traits::input_parameter< uint >::type seed(seedSEXP);
                                                 ^~~~
RcppExports.cpp:24:100: error: 'seed' was not declared in this scope
     rcpp_result_gen = Rcpp::wrap(fit_sampleqc_mle_cpp(x, init_gamma_i, groups, D, J, K, N, n_iter, seed));
                                                                                                    ^~~~
RcppExports.cpp:24:100: note: suggested alternative: 'fseek'
     rcpp_result_gen = Rcpp::wrap(fit_sampleqc_mle_cpp(x, init_gamma_i, groups, D, J, K, N, n_iter, seed));
                                                                                                    ^~~~
                                                                                                    fseek
RcppExports.cpp: At global scope:
RcppExports.cpp:29:156: error: 'uint' has not been declared
 List fit_sampleqc_robust_cpp(arma::mat x, arma::uvec init_z, arma::uvec groups, int D, int J, int K, int N, int em_iters, double mcd_alpha, int mcd_iters, uint seed, bool track);
                                                                                                                                                            ^~~~
RcppExports.cpp: In function 'SEXPREC* _SampleQC_fit_sampleqc_robust_cpp(SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP, SEXP)':
RcppExports.cpp:44:36: error: 'uint' was not declared in this scope
     Rcpp::traits::input_parameter< uint >::type seed(seedSEXP);
                                    ^~~~
RcppExports.cpp:44:36: note: suggested alternative: 'Sint'
     Rcpp::traits::input_parameter< uint >::type seed(seedSEXP);
                                    ^~~~
                                    Sint
RcppExports.cpp:44:41: error: template argument 1 is invalid
     Rcpp::traits::input_parameter< uint >::type seed(seedSEXP);
                                         ^
RcppExports.cpp:44:49: error: expected initializer before 'seed'
     Rcpp::traits::input_parameter< uint >::type seed(seedSEXP);
                                                 ^~~~
RcppExports.cpp:46:121: error: 'seed' was not declared in this scope
     rcpp_result_gen = Rcpp::wrap(fit_sampleqc_robust_cpp(x, init_z, groups, D, J, K, N, em_iters, mcd_alpha, mcd_iters, seed, track));
                                                                                                                         ^~~~
RcppExports.cpp:46:121: note: suggested alternative: 'fseek'
     rcpp_result_gen = Rcpp::wrap(fit_sampleqc_robust_cpp(x, init_z, groups, D, J, K, N, em_iters, mcd_alpha, mcd_iters, seed, track));
                                                                                                                         ^~~~
                                                                                                                         fseek
RcppExports.cpp: At global scope:
RcppExports.cpp:51:19: error: variable or field 'set_seed_cpp' declared void
 void set_seed_cpp(uint seed);
                   ^~~~
RcppExports.cpp:51:19: error: 'uint' was not declared in this scope
RcppExports.cpp:51:19: note: suggested alternative: 'Sint'
 void set_seed_cpp(uint seed);
                   ^~~~
                   Sint
RcppExports.cpp: In function 'SEXPREC* _SampleQC_set_seed_cpp(SEXP)':
RcppExports.cpp:55:36: error: 'uint' was not declared in this scope
     Rcpp::traits::input_parameter< uint >::type seed(seedSEXP);
                                    ^~~~
RcppExports.cpp:55:36: note: suggested alternative: 'Sint'
     Rcpp::traits::input_parameter< uint >::type seed(seedSEXP);
                                    ^~~~
                                    Sint
RcppExports.cpp:55:41: error: template argument 1 is invalid
     Rcpp::traits::input_parameter< uint >::type seed(seedSEXP);
                                         ^
RcppExports.cpp:55:49: error: expected initializer before 'seed'
     Rcpp::traits::input_parameter< uint >::type seed(seedSEXP);
                                                 ^~~~
RcppExports.cpp:56:18: error: 'seed' was not declared in this scope
     set_seed_cpp(seed);
                  ^~~~
RcppExports.cpp:56:18: note: suggested alternative: 'fseek'
     set_seed_cpp(seed);
                  ^~~~
                  fseek
RcppExports.cpp:56:5: error: 'set_seed_cpp' was not declared in this scope
     set_seed_cpp(seed);
     ^~~~~~~~~~~~
make: *** [C:/PROGRA~1/R/R-41~1.1/etc/x64/Makeconf:245: RcppExports.o] Error 1
ERROR: compilation failed for package 'SampleQC'
* removing 'C:/Users/mdmanurung/Dropbox/PhD/projects/czi-scrnaseq/renv/library/R-4.1/x86_64-w64-mingw32/SampleQC'
Warning messages:
1: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir, restore_times) :
  skipping pax global extended headers
3: In i.p(...) :
  installation of package ‘C:/Users/MDMANU~1/AppData/Local/Temp/RtmpaY4LBP/file14a646e8e3440/SampleQC_0.6.3.tar.gz’ had non-zero exit status

</p>
</details>  

<details>
  <summary> And here is my `sessionInfo()` output</summary>
  
  R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    
system code page: 65001

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

loaded via a namespace (and not attached):
 [1] processx_3.5.2      BiocManager_1.30.16 compiler_4.1.1      R6_2.5.1           
 [5] rprojroot_2.0.2     cli_3.0.1           prettyunits_1.1.1   tools_4.1.1        
 [9] withr_2.4.2         crayon_1.4.1        remotes_2.4.0       callr_3.7.0        
[13] ps_1.6.0            pkgbuild_1.2.0      renv_0.14.0       
</details>

I have ensured rtools to be properly installed and make can be found by `Sys.which("make")`. Do you have any idea on what causing this problem?

Thanks in advance.

**EDIT**: I tried installing SampleQC in a linux workstation and it worked just fine.

Regards,
Mikhael

**Comment by wmacnair** [comment]
Hey Mikhael

Thanks for pointing this out. I don't have a Windows machine so will be a bit tricky for me to check this, but I'll try to look into it. 

Glad you could get it to work on Linux. Out of curiosity, is your Linux workstation also running `R 4.1.x`? I haven't tested `SampleQC` with `R 4.1.x` myself yet, curious if it's ok.

Will

**Comment by bugneville** [comment]
@wmacnair, I similarly tried to installed in Win10 (R 4.1.2) with the equivalent error and so I ended up running in linux where it installed w/o complaint (R 4.1.2, Ubuntu 20.04.3).  However, I was unable to work my way through your README.md steps with my data and resorted to working through your [preprint github](https://github.com/wmacnair/SampleQC_paper_analyses), which looked to work, so I suspect my data is just ill-formed.

**a couple notes from running your code?**
- qc01: no "data/miqc" in github, didn't evaluate
- qc02: runs after fixing capitalization differences b/w files & datasets object
- qc03: ran w/o edits
- qc04: changed "splice_ratio" to "log_feats" in `qc_names` and skipped making "med_splice" field, to run
- qc05: removed call to your local SampleQC in code/qc05_citeseq.R to run.  unclear where neg_obj & test_obj are coming from?; didn't evaluate further
- qc06: runs until: `g = plot_sample_fits(fit_list, K_grid, pr_by_sim)` returns: `In min(def_dist) : no non-missing arguments to min; returning Inf`, which causes `for (f in formats) ggsave(sprintf(k_vs_k_f, f), g, h = 10, w = 8)` to return: `Error: Faceting variables must have at least one value`.

Apologies for not knowing more to further diagnose.

**Comment by wmacnair** [comment]
Hi @bugneville, thanks for your detailed comments and sorry I've been so long to get to them. I have a full-time only non-academic job now, which makes finding time a bit tricky...

I've made some tweaks to both `SampleQC` and `SampleQC_paper_analyses` that should fix the issues you brought up. There were a couple that weren't actually issues for me: the capitalization issue; the `plot_sample_fits` call. 

I'd be very happy to reopen and make further tweaks if you identify anything else. But I also won't be at all surprised if you've now moved on to something else...!

Cheers
Will

**Comment by wmacnair** [comment]
Hi @mdmanurung

In principal this should now be fixed (I replaced `uint` with `unsigned int`) but I don't have a windows machine so haven't been able to test it myself. If you have time and can confirm, that would be great :)

Will
